[build]
  command = ""    # no build step for static
  publish = "."

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"
